name: CI - DVC Repro & MLflow Log

# Pemicu kapan workflow ini harus dijalankan
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Daftar pekerjaan (jobs) yang harus dilakukan
jobs:
  # Nama pekerjaan pertama: 'linter-check' (CI)
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linter with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv

  # Nama pekerjaan kedua: 'run-ml-pipeline' (CI untuk ML)
  run-ml-pipeline:
    # Pekerjaan ini hanya akan dijalankan jika 'linter-check' berhasil
    needs: linter-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DVC pipeline
        run: dvc repro

      - name: Upload ML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            reports/metrics.json
            models/model.joblib
            mlruns/
